### ISSUE TITLE
Format Result as Fraction

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [mkulesh/microMathematics#119]
Feature Request

It would be useful to be able to format a result as a fraction, or allow the decimal portion of a result as a fraction, similar to SI architectural measurements (i.e. 8.791666666667 feet vs 8'-9 1/2").

Just discovered microMath, and it looks like an excellent open source alternative to MathCAD!

**Comment by mkulesh** [comment]
Hi @shrimprugbysnowowl 
thank you for the proposal. I will try to add this possibility using https://commons.apache.org/proper/commons-numbers/ libraries. 
More technical information: the similar question was discussed on https://stackoverflow.com/questions/474535/best-way-to-represent-a-fraction-in-java

**Comment by mkulesh** [comment]
Hi @shrimprugbysnowowl 
I implemented a first drop of the fraction representation:
![fraction](https://user-images.githubusercontent.com/30557348/197350743-043a6cd5-9e93-4503-b1ec-d6598bdb808f.png)

The fraction representation is activated in the result property dialog that appears when you long press on the result formula and than press "Object property" floating button:
![fraction1](https://user-images.githubusercontent.com/30557348/197351717-856e7097-4b21-49c9-8261-1a1aacb41c30.png)

It works, but some points are not really clear for me:
- Currently, the numerator can be greater than denominator, i.e a common integer part exists. Shall I extract this common integer part and show it separately, like 1.5 = 1 1/2 (currently it is shown as 3/2)?
- The complex numbers are shows as it is, without fraction since the representation like 3/2 - i 5/7 may be not really readable. Are you agree with this restriction.

Do you like to have an APK for the testing?

**Comment by shrimprugbysnowowl** [comment]
Very cool!  When I submitted the suggestion, I was using the app to perform calculations in imperial architectural units which are typically shown as:
[integer feet] - [integer inches] [fractional inch]
As it relates to this app, I personally think it would be useful to show integers separately from a fraction, but someone may also want the option to show "improper fractions".

I don't have enough exposure with complex numbers to have an opinion if fractions should be used with "i". Sorry

I'd love an APK for testing! Awesome work!

**Comment by mkulesh** [comment]
Hi @shrimprugbysnowowl 
thanks, I will modify the representation in order to show integers separately from a fraction and provide you a test APK tomorrow.

**Comment by mkulesh** [comment]
Hi @shrimprugbysnowowl 

please download and manually install this test APK:  https://1drv.ms/u/s!At2sh2-YDyGFgSYciWpo4LRq-roW?e=ood4II

It is just an initial implementation, some bugs can exist here and I still testing it.

**Comment by mkulesh** [comment]
To be merged into free version
