### ISSUE TITLE
add CAS

### ISSUE THREAD

**Issue by tino1003870** [mkulesh/microMathematics#123]
To replace a TI-Nspire, is the a chance to add some algebra funcionality to this golden piece of software in future?

**Comment by mkulesh** [comment]
Hi @tino1003870 
I am not too familiar with TI-Nspire. Could you please write more detailed which functionality do you need? Some examples how does it look on TI-Nspire will be also helpful.

**Comment by tino1003870** [comment]
Hi Mikhail,

ignore NSpire ... GIAC is at least the same or better equivalent 
(https://www-fourier.ujf-grenoble.fr/~parisse/giac.html)

Best,
Tino

**Comment by mkulesh** [comment]
Hi @tino1003870 
the library is not a problem. I use internally Apache Common Math library that also have different algebra functionality... I asked about use cases that are helpful for the end users... Could you just list which algebra functionality is missing and can be helpful for the users?

**Comment by tino1003870** [comment]
Hi Mikhail,

got it. The following would help a lot (listed in priority order):
(1) unit handling 
(https://www-fourier.ujf-grenoble.fr/~parisse/giac/doc/en/cascmd_en/node609.html)
(2) nsolve 
(https://www-fourier.ujf-grenoble.fr/~parisse/giac/doc/en/cascmd_en/node593.html)
(maybe 3) solve, csolve, desolve 
(https://www-fourier.ujf-grenoble.fr/~parisse/giac/doc/en/cascmd_en/node522.html)

Does it help?

Best,
Tino

**Comment by mkulesh** [comment]
Hi @tino1003870 

my app is already able to handle units. For documentation, please take a look on the files units_overview.mm and units_of_information.mmt from the "Resources of microMathematics Plus". To open resources, use "Open file" from main menu, than press "Home" button, and, finally navigate to  the "Resources of microMathematics Plus".

Internally, I use Apache Common Math library that also provides a lot of different algorithms. It also has a good algorithms for the root finding: https://commons.apache.org/proper/commons-math/userguide/analysis.html
If I will add something like root solving for a function of one argument, I will prefer Apache Common Math since it is API-compatible. I do not see any cheap possibility to use a C++ library in my app.

**Comment by mkulesh** [comment]
Currently, no plan to fix it
