### ISSUE TITLE
Input operands by typing symbols

### ISSUE THREAD

**Issue by dogtopus** [mkulesh/microMathematics#16]
It would be nice to recognize the input of basic arithmetic and logic symbols (+-*/^<>, etc.) and automatically insert a corresponding operand to the desired position (with LHS defaults to the nearest symbol/operand)

**Comment by mkulesh** [comment]
Dear @dogtopus, thank you for submitting an issue. The microMathematics can already recognize the input of basic arithmetic and logic symbols from the keyboard. For example, if you put the symbol "*" from the keyboard, the multiplication operator with two terms will be automatically inserted. There is just a special case for "plus" and "minus" operators: "plus" operator will be created if you put "++" (since the single symbol "+" is used as a part of a complex number). "minus" operator will be created if you put "--." To see which operator corresponds to which keyboard shortcut, just long click on the corresponding button from the mathematical palette and observe the hint that appears from this long click. If it is not the desired behavior for you, could you please formulate the behavior that you wont more concrete? If this behavior is OK for you, please close the issue.

**Comment by dogtopus** [comment]
Thanks for clarify. This is exactly what I want.
