### ISSUE TITLE
Import/Export SMath Studio document (*.sm)

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#38]
Since documents' format of SMath Studio (freeware desktop software, similar to MathCAD & μMath+) is open & XML-based, think, its possible add support for import/export SM files (extension: `.sm`)
* https://smath.info/
  * https://smath.info/wiki
  * https://smath.info/svn/public

Some tools, that could be usefull
* https://github.com/shotInLeg/SMathParser
* https://github.com/jonasmr/smath

P.S.: Soon will try add some examples

**Comment by mkulesh** [comment]
There is a plug-in for SMath Studio, that allows to open "mmt" file stored in uMath+
https://en.smath.info/view/17b48bca-9378-492d-9fbf-dfe8db26d1fa/history

However, some part of mathematical content of uMath+ is currently not fully supported by this plug-in.
I collected and tested supported functionality in this document:
[Functions Overview](http://htmlpreview.github.io/?https://github.com/mkulesh/microMathematics/blob/master/doc/functions_overview.html)

All expressions listed in this document can be now opened in  SMath Studio:
![opening_mmt_in_smath_studio](https://user-images.githubusercontent.com/30557348/34898350-eb02d644-f7f2-11e7-99cc-37c4d751176f.png)

All expression not listed in this document may work, but also may yet *not* work. I work together with Andrey Ivashov, the author of SMath Studio, in order to improve SMath Studio integration and expand the set of supported features. 

If you like to test it, please try to open your existing uMath+ calculations in SMath Studio

**Comment by mkulesh** [comment]
Hi @Symbian9, uMath+ is now able to directly open SMath Studio files. Of course, not all mathematical functionality of SMath Studio is supported by uMath+.  I invite you to test this feature.

**Comment by Symbian9** [comment]
@mkulesh, COOL! I will test it! ;-)

**Comment by mkulesh** [comment]
Released in version 2.17.0
