### ISSUE TITLE
Content of opened document fully removed if close app without saving results

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#62]
Its look like critical bug found on replacing source file if nothing saved on exit or closing app.

REPRODUCING:

1. Download `units_overview.mmt` and save on device, check its file size (I just save it in `/sdcard/documents` folder)
2. Run *μMath+*
3. Open document `/sdcard/documents/units_overview.mmt`
4. Run calculating and wait for completing
5. Close app
6. RESULT: File `/sdcard/documents/units_overview.mmt` **rewrited by zero-bytes file!**

μMath+ Version: latest `autobuild` (2.17.x)

**Comment by mkulesh** [comment]
Hi, @Symbian9,
many-many thanks for the problem report.

Unfortunately, I can not reproduce the problem on a real device (Xiaomi RN4, Android 6). Later, I will try it on different emulators. Could you give me more details that can help me to identify the problem:

- is it happens with units_overview.mmt only or with other files as well?
- if the problem happens with other files, are new units used in these files? Can the problem be reproduced for a worksheet that does not use units?
- which Android version do you have?
- Is there any difference if you store the file into the internal memory rather than on a physical SD-card?
- Has your Android any settings like "Immediately kill the app on exit" from performance or energy saving reason?

I ask since the auto-save on exit is implemented synchronously (not a background job) and has no changes in this release. I think this problem is ether system-dependent or happens due to some bug in the new units calculation feature that prevents the successful auto-save.

**Comment by mkulesh** [comment]
Hi @Symbian9,
I tryed to reproduce this case on different devices (Lenovo, Xiaomy, Nokia) and on emulators for all supported Adroid version. However, I still not be able to reproduce it.
Still the problem reproducable on your device?

**Comment by mkulesh** [comment]
Closed since can not be reproduced.
