### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mihapiha** [mkulesh/microMathematics#64]
It would be really nice if we could define custom dataset to work on. Like an interval where all values are user defined

**Comment by mkulesh** [comment]
Thanks for the proposal. I will try to implement it whether in version 2.17.1, or in the next version.

**Comment by mkulesh** [comment]
Hi @mihapiha, currently, you can define custom dataset in a text file (just one value per row for one-dimensional dataset or a space-separated table for two-dimensional dataset). This file can be prepared in any editor and than opened in microMathematics using "read" function. May be this method can cover some of your cases as long as this issue still not yet implemented.

**Comment by mkulesh** [comment]
Hi @mihapiha, I started to work on this issue. There are already two features released in version 2.18.0: #83 and #86. Now, the elements of a custom dataset can be directly assigned using indices. I still working on this issue in order to implement other ways to define custom dataset like a direct editing of a vector or matrix.
