### ISSUE TITLE
Allow change app locale independently from current system locale

### ISSUE THREAD

**Issue by Symbian9** [mkulesh/microMathematics#8]
Make app locale indepedent from system locale.

**Comment by mkulesh** [comment]
Dear @Symbian9, your request is implemented. Now, there is a new menu "App language" that allows to select between english/russian/german. As long as there is only one application parameter, I decided to not add at this stage settings activity but just select this parameter in a selection dialog directly. Could you please test the implementation and close the issue if everything is OK?

**Comment by Symbian9** [comment]
> Could you please test the implementation 

@mkulesh, of course! Where get this APK for testing?

**Comment by mkulesh** [comment]
Please download
https://github.com/mkulesh/microMathematics/blob/master/release/microMathematics-v2.15.4a.apk

**Comment by Symbian9** [comment]
> Please download

OK, its work. But need rework application settings dialog (will give you some mockups soon as separate issue)

**Comment by mkulesh** [comment]
Dear @Symbian9, I reworked the language selection. Instead of separate menu for the language selection, I introduced the application settings activity and moved language selection there. 
https://github.com/mkulesh/microMathematics/blob/master/release/microMathematics-v2.15.4a.apk is rebuild. Please look at the new implementation.

**Comment by Symbian9** [comment]
> Please look at the new implementation.

Yeah, now it look much better. Now I test it
