### ISSUE TITLE
Symbol is not a known variable or argument

### ISSUE THREAD

**Issue by StragaSevera** [mkulesh/microMathematics#95]
I have a very simple sheet, but it does not calculate and gives me errors:
http://imgur.com/a/MPuCJqh

**Comment by mkulesh** [comment]
Hi @StragaSevera,
I am sorry that this part of the app is a little bit complicated. Instead of put the "minus" symbol from the keyboard, please try to press "Minus" button from the bottom tool panel. The problem it that the simple "minus" symbol is used as a separator in the complex numbers. If you need a "minus" operator you shall ether press a corresponding button from the tool panel or use a shortkey "--" (minus symbol pressed two times) from the keyboard. The same problem is with "plus" operator; you need to put "++" for it from the keyboard.
I known it is not really intuitive. I plan to fix this behavior in the next releases.
